CODEOWNERS, CONTRIBUTORS.md, COPYRIGHT.txt
=> Init basic repo

content/sigstore-january-roundup-09isdj30idoj.md
Signed-off-by: Mathieu Benoit <mathieu-benoit@hotmail.fr>
Fix typo in title with `Janaury`
=> Fix typo in title with Janaury

themes/pixyll/layouts/partials/navigation.html
Otherwise the URL is https://blog.sigstore.dev//about/
Signed-off-by: Hayden B <hblauzvern@google.com>
=> Remove extra slash on about

content/its-ten-o-clock-do-you-know-where-your-private-keys-are-5c869cf53234.md, content/signatus-ergo-securus-who-can-sign-what-with-tuf-and-sigstore-ea4d3d84b8b6.md, content/sigstore-project-update-august-2021-1fad6d12b8dc.md, content/sigstore-project-update-september-2021-799162b5a686.md, content/sigstore-software-signing-for-everybody-has-been-published-in-the-proceedings-of-the-acm-bb7e7d679a73.md
Add +++ where missing, and make author a single string
Fixes https://github.com/sigstore/sigstore-blog/issues/16
Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>
=> Fix metadata issues

content/adopting-sigstore-incrementally-1b56a69b8c15.md
=> Fix title for Adopting Sigstore Incrementally

content/about.md
=> Update about page

content/npm-public-beta.md
=> Update npm-public-beta with headers

content/case-study-smallstep.md
=> Fix image link

content/announcing-sig-clients.md
=> Add "announcing sig-clients" post.

content/openpubkey-and-sigstore.md
=> Fix a few typos in the first draft of the OpenPubKey post.

content/is-sigstore-ready-for-a-post-quantum-world-82c9166985af.md
=> Fix table in post-quantum blog post

.gitignore
=> gitignore for blog

content/sigstore-november-roundup-2023.md
Note, news was gathered with Google News 1 Oct 2023 – 30 Nov 2023
From now on, will limit to a month
=> November 23 Project Update

content/sigstore-feb24-roundup-2024.md
=> February roundup

content/sigstore-feb24-roundup-2024.md
Include SOSS Community Day talks, update OSS NA talks, fix capitalization
=> Updates to February post

content/sigstore-openssf-graduation.md
=> Blog post for OSSF Graduation

content/cosign-verify-bundles.md
There's some really cool features in the cosign v2.4.0 release that allows you to verify attestations in the bundle format used by npm provenance, GitHub Artifact Attestations, and Homebrew provenance. Let's show people how it works!
NONE
N/A
=> Post about verifying bundles from various services with cosign

content/fulcio-ci-provider.md
=> Blog post for fulcio CI identity provider onboarding

.github/workflows/ci-build.yml, .github/workflows/hugo.yml
=> Bump GitHub Actions deps to latest version

content/sigstore-december-roundup-7b5ebaac3442.md, content/sigstore-november-roundup-8a852cec10fc.md, content/sigstore-october-roundup-80d476308b75.md, content/sigstore-update-august-2022-813ac2c7c9ef.md, content/spooky-october-updates-for-sigstore-87a2b72172c1.md, content/whats-next-for-sigstore-1969e7321f75.md
=> Remove references to deleted twitter accounts

content/terraform-modules.md
Short blog post on the new terraform-modules repository along with the deprecation of the tf configs under scaffolding.
=> Terraform modules blog post

content/rekor-v2-alpha.md
This details the upcoming alpha release of Rekor v2, where we will provide a code-complete server for developers to test.
Fixes https://github.com/sigstore/rekor-tiles/issues/172
=> Rekor v2 alpha launch blog post
